name: Deploy To Firebase
on:
  workflow_dispatch:
     inputs:
       release_notes:
         type: string
         required: true
         default: 'Manual Deploy'
         description: 'Input for Release Notes'

jobs:
  build:
    name: Building and distributing app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: SetUp Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version : '17'
          distribution : 'corretto'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.0.0-beta.3

      - name: Build Gradle
        run: ./gradlew build

      - name: Execute Gradle Command - assembleDebug
        run: ./gradlew assembleDebug

      - name: Upload Artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: qa
          file: app/build/outputs/apk/debug/app-debug.apk
          releaseNotes: ${{ inputs.release_notes }}
